version: '3.8'

services:
  rxinfer-server:
    build:
      context: ../../..
      dockerfile: Dockerfile
    image: rxinfer-kserve:latest
    container_name: rxinfer-streaming-server
    ports:
      - "8090:8080"  # HTTP API (mapped to 8090 to avoid conflicts)
      - "8091:8081"  # gRPC API (mapped to 8091 to avoid conflicts)
    environment:
      - JULIA_NUM_THREADS=4
      - RXINFER_LOG_LEVEL=info
    volumes:
      - ../server/streaming_model.jl:/app/streaming_model.jl:ro
    command: ["julia", "--sysimage=/app/rxinfer-kserve.so", "--project=.", "/app/streaming_model.jl"]
    healthcheck:
      test: ["CMD", "bash", "-c", "curl -f http://localhost:8080/v2/health/live && curl -f http://localhost:8080/v2/models"]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 30s
    networks:
      - rxinfer-net

  streaming-client:
    build:
      context: ../../..
      dockerfile: examples/infinite_stream_demo/client/Dockerfile
    image: rxinfer-streaming-client:latest
    container_name: rxinfer-streaming-client
    depends_on:
      rxinfer-server:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=${DISPLAY:-}
      - MPLBACKEND=Agg
    volumes:
      - ./results:/app/results
    networks:
      - rxinfer-net
    stdin_open: true
    tty: true
    command: ["python", "streaming_client.py"]

networks:
  rxinfer-net:
    driver: bridge

volumes:
  results: